Material Dark Red theme
maartenpaauw/home-assistant-community-themes pull request #1
Opened 2019-01-05 00:00 UTC by 95gabor

![image](https://user-images.githubusercontent.com/6538843/50717092-4f619200-1085-11e9-8c80-3051f5478607.png)

2019-01-05 10:13 UTC, maartenpaauw commented
Hello @95gabor!

Thanks for adding you theme. It looks nice!
I've added a comment to one of the files.
Could you please fix that?

Once it is fixed I'll merge the pull request.

Thanks!

2019-01-05 12:19 UTC, 95gabor commented
> Hello @95gabor!
> 
> Thanks for adding you theme. It looks nice!
> I've added a comment to one of the files.
> Could you please fix that?
> 
> Once it is fixed I'll merge the pull request.
> 
> Thanks!

Hi @maartenpaauw!

I'm on it to fix it. Which comment do you mean?

Thanks!

2019-01-05 12:50 UTC, maartenpaauw commented
Hello @95gabor,

The comments are listed above 😃.

2019-01-28 09:15 UTC, maartenpaauw requested changes

2019-01-28 09:15 UTC, maartenpaauw commented on material_dark_red.yaml
> +  table-row-alternative-background-color: "var(--sidebar-text_-_background)"
@95gabor Could you please add a new line at the end of this file?

2019-01-28 09:15 UTC, maartenpaauw commented on README.md
> +| Material Dark Red   | [95gabor](https://community.home-assistant.io/u/95gabor) posted [Material dark red theme](#)                 | material_dark_red |
@95gabor Did you submit your theme to the community forum? If so, you can put the link at the #.

2019-01-28 13:14 UTC, maartenpaauw commented
> Hi @maartenpaauw!
> 
> I'm on it to fix it. Which comment do you mean?
> 
> Thanks!

Oops.. I forgot to start the review process. You should be able to see the comments right now.

2019-02-21 12:27 UTC, 95gabor commented on material_dark_red.yaml
> +  table-row-alternative-background-color: "var(--sidebar-text_-_background)"
@maartenpaauw new line added in this commit:  https://github.com/maartenpaauw/home-assistant-community-themes/pull/1/commits/39a3d257d49d93c14ae893b910be3e759b7d6d0d

2019-02-21 12:29 UTC, 95gabor commented on README.md
> +| Material Dark Red   | [95gabor](https://community.home-assistant.io/u/95gabor) posted [Material dark red theme](#)                 | material_dark_red |
@maartenpaauw I made a new topic for this theme. README link updated in https://github.com/maartenpaauw/home-assistant-community-themes/pull/1/commits/39a3d257d49d93c14ae893b910be3e759b7d6d0d

2019-02-21 12:42 UTC, maartenpaauw approved these changes

2019-02-21 12:42 UTC, merged