Amoled theme
maartenpaauw/home-assistant-community-themes pull request #2
Opened 2019-01-27 18:43 UTC by lance36

theme optimized for amoled screens

2019-01-28 09:10 UTC, maartenpaauw commented
Hello @lance36,

Thanks for your submission! Great work!
I'll leave some comments at the code.

Maarten

2019-01-28 09:15 UTC, maartenpaauw requested changes

2019-01-28 09:15 UTC, maartenpaauw commented on README.md
> +| Amoled          | [lance36](https://community.home-assistant.io/u/lance36) posted [Amoled Theme](https://community.home-assistant.io/t/amoled-theme/94875)
Could you please put your theme at the top of the list?
It's alphabetical ordered (based on variable name).

2019-01-28 09:15 UTC, maartenpaauw commented on amoled.yaml
> +  # Main colors
Could you please remove all comments in this file?

2019-01-28 09:15 UTC, maartenpaauw commented on amoled.yaml
> +  primary-color: '#484A4C'                                                        # Header
Could you please replace all single quotes with double quotes in this file?

2019-01-28 09:15 UTC, maartenpaauw commented on amoled.yaml
> +
Could you please remove all blank lines in this file?

2019-01-28 09:15 UTC, maartenpaauw commented on amoled.yaml
> +  google-green-500: '#39E949'
Could you please add a newline at the end of this file?

2019-01-28 12:56 UTC, lance36 commented
i think i fucked up a bit, trying to learn git :)

should be ok now, all changes suggested were made

2019-01-28 13:17 UTC, maartenpaauw commented
> i think i fucked up a bit, trying to learn git :)
> 
> should be ok now, all changes suggested were made

@lance36 no problem! Learning is good!

There are now 2 newlines at the end of the file. You can remove 1. There is only 1 needed. 

When you removed the comments (at the end of the lines) you forgot to remove the leading spaces (check screenshot). 

<img width="843" alt="screen shot 2019-01-28 at 14 15 54" src="https://user-images.githubusercontent.com/4550875/51838688-5b004b80-2307-11e9-8a6d-f119422abc2a.png">

If you fix these two things I can merge the PR.

Thanks again!

2019-01-28 13:33 UTC, lance36 commented
Done

2019-01-31 14:26 UTC, maartenpaauw requested changes

2019-01-31 14:26 UTC, maartenpaauw commented on amoled.yaml
> +  paper-toggle-button-unchecked-ink-color: "var(--disabled-text-color)"
You missed one space :)

2019-01-31 17:29 UTC, merged

2019-01-31 17:30 UTC, maartenpaauw commented
Thanks for your time and submission 👍🏻