Add Nord theme
maartenpaauw/home-assistant-community-themes pull request #8
Opened 2019-08-03 08:47 UTC by JayBigGuy10

I had no idea how to add to my last merge request so I closed them and opened this one with both files

2019-08-03 14:27 UTC, maartenpaauw commented on README.md
> +| Nord            | [Jasperro](https://community.home-assistant.io/u/jasperro) posted [Nord Theme](https://community.home-assistant.io/t/nord-theme/129301)             | nord                |
Could you please leave this list alphabetical ordered (based on theme name)?

2019-08-03 14:27 UTC, maartenpaauw requested changes

2019-08-03 14:27 UTC, maartenpaauw commented on nord.yaml
> +  sidebar-icon-color: "var(--foreground-color)"
Is there an extra blank line at the end of this file?

2019-08-03 14:27 UTC, maartenpaauw commented on README.md
> +| Nord            | [Jasperro](https://community.home-assistant.io/u/jasperro) posted [Nord Theme](https://community.home-assistant.io/t/nord-theme/129301)             | nord                |
Could you please leave this list alphabetical ordered (based on theme name)?

2019-08-03 14:28 UTC, maartenpaauw commented
Thanks for combining the pull requests. I left 2 comments on the code. If you could fix this I'm happy to merge the PR.

2019-08-06 03:44 UTC, JayBigGuy10 commented
Hi I have updated the files

2019-08-08 14:42 UTC, maartenpaauw approved these changes

2019-08-08 14:42 UTC, merged